server:
  port: 5600

static:
  path: /app/static

# 是否为演示环境
demo: false

log:
  path: /var/log
  level: debug
  apm:
    enable: true
    url: http://43.143.195.208:5080
    authorization: Basic amlhbmd3MTAyN0BnbWFpbC5jb206YWxsaW9AMjAyMw==
    organization: default
    stream: fusion

codeRunner:
  path: /app/codeRunner

pluginRunner:
  path: /app/pluginRunner

mongodb:
  # 如果存在url就不需要填写下面属性
  url: mongodb://root:123456@43.143.195.208:27017/?retryWrites=true&w=majority
  host: 43.143.195.208
  port: 27017
  username: root
  password: 123456
  db: fusion

